# Generated by Django 3.2.6 on 2021-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='ID користувача')),
                ('name', models.CharField(max_length=128, verbose_name="Ім'я користувача")),
            ],
            options={
                'verbose_name': 'Профіль',
            },
        ),
    ]
