# Generated by Django 3.2.6 on 2021-09-01 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='property_prof',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.property', verbose_name='Профиль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='property_prof',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.property', verbose_name='Профиль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='property_prof',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.property', verbose_name='Профиль'),
            preserve_default=False,
        ),
    ]
