# Generated by Django 3.2.6 on 2021-09-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_property_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=22),
            preserve_default=False,
        ),
    ]
